package problems.p2;

public class P2 {
	/*
	 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
	 * 
	 *    1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
	 *  
	 *  By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
	 */

	/**
	 * @param args
	 */
	public static void main(String[] args) {
		System.out.println(sumFib(100));
		System.out.println(sumFib(4000000L));
	}
	
	public static long sumFib(long cap) {
		long prev = 1;
		long current = 2;
		long sum = 0;
		
		while (current < cap) {
			if ((current & 0x1) == 0) {
				sum += current;
			}
			
			long next = prev + current;
			prev = current;
			current = next;
		}
		
		return sum;
	}

}
